__doc__ = "This module 'vode' is auto-generated with f2py (version:2).\nFunctions:\n  y,t,istate = dvode(f,jac,y,t,tout,rtol,atol,itask,istate,rwork,iwork,mf,f_extra_args=(),jac_extra_args=(),overwrite_y=0)\n  y,t,istate = zvode(f,jac,y,t,tout,rtol,atol,itask,istate,zwork,rwork,iwork,mf,f_extra_args=(),jac_extra_args=(),overwrite_y=0)\n."
__file__ = '/home/nj/.conda/envs/cs231n/lib/python3.6/site-packages/scipy/integrate/vode.cpython-36m-x86_64-linux-gnu.so'
__name__ = 'scipy.integrate.vode'
__package__ = 'scipy.integrate'
__version__ = b'$Revision: $'
def dvode():
    "y,t,istate = dvode(f,jac,y,t,tout,rtol,atol,itask,istate,rwork,iwork,mf,[f_extra_args,jac_extra_args,overwrite_y])\n\nWrapper for ``dvode``.\n\nParameters\n----------\nf : call-back function\njac : call-back function\ny : input rank-1 array('d') with bounds (neq)\nt : input float\ntout : input float\nrtol : input rank-1 array('d') with bounds (*)\natol : input rank-1 array('d') with bounds (*)\nitask : input int\nistate : input int\nrwork : input rank-1 array('d') with bounds (lrw)\niwork : input rank-1 array('i') with bounds (liw)\nmf : input int\n\nOther Parameters\n----------------\nf_extra_args : input tuple, optional\n    Default: ()\njac_extra_args : input tuple, optional\n    Default: ()\noverwrite_y : input int, optional\n    Default: 0\n\nReturns\n-------\ny : rank-1 array('d') with bounds (neq)\nt : float\nistate : int\n\nNotes\n-----\nCall-back functions::\n\n  def f(t,y): return ydot\n  Required arguments:\n    t : input float\n    y : input rank-1 array('d') with bounds (n)\n  Return objects:\n    ydot : rank-1 array('d') with bounds (n)\n  def jac(t,y): return jac\n  Required arguments:\n    t : input float\n    y : input rank-1 array('d') with bounds (n)\n  Return objects:\n    jac : rank-2 array('d') with bounds (nrowpd,n)\n"
    pass

def zvode():
    "y,t,istate = zvode(f,jac,y,t,tout,rtol,atol,itask,istate,zwork,rwork,iwork,mf,[f_extra_args,jac_extra_args,overwrite_y])\n\nWrapper for ``zvode``.\n\nParameters\n----------\nf : call-back function\njac : call-back function\ny : input rank-1 array('D') with bounds (neq)\nt : input float\ntout : input float\nrtol : input rank-1 array('d') with bounds (*)\natol : input rank-1 array('d') with bounds (*)\nitask : input int\nistate : input int\nzwork : input rank-1 array('D') with bounds (lzw)\nrwork : input rank-1 array('d') with bounds (lrw)\niwork : input rank-1 array('i') with bounds (liw)\nmf : input int\n\nOther Parameters\n----------------\nf_extra_args : input tuple, optional\n    Default: ()\njac_extra_args : input tuple, optional\n    Default: ()\noverwrite_y : input int, optional\n    Default: 0\n\nReturns\n-------\ny : rank-1 array('D') with bounds (neq)\nt : float\nistate : int\n\nNotes\n-----\nCall-back functions::\n\n  def f(t,y): return ydot\n  Required arguments:\n    t : input float\n    y : input rank-1 array('D') with bounds (n)\n  Return objects:\n    ydot : rank-1 array('D') with bounds (n)\n  def jac(t,y): return jac\n  Required arguments:\n    t : input float\n    y : input rank-1 array('D') with bounds (n)\n  Return objects:\n    jac : rank-2 array('D') with bounds (nrowpd,n)\n"
    pass

